/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin.Food;

import ui.admin.*;
import Business.EcoSystem;
import Business.Organization.FoodOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author mrudu
 */
public class RevenueGenerated extends javax.swing.JPanel {

    /**
     * Creates new form RevenueGenerated
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    EcoSystem system;
    JSplitPane adminSplitPane;
    Organization organization;
    FoodOrganization foodOrg;
    
    //HashMap map = new HashMap();
    Map<List<String>,Double> map = new LinkedHashMap<>();
    static int rVal, bVal, gVal;
    public RevenueGenerated(JPanel userProcessContainer, UserAccount userAccount, EcoSystem system, JSplitPane adminSplitPane, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.organization = organization;
        
        if(organization.getName().equals("Food Organization")){
                foodOrg = ((FoodOrganization) organization);
                System.out.println("foodOrg name>>"+foodOrg.getName());
        }else{
            System.out.println("something is wrong");
        }
        
        foodOrg.generateMap();
        foodOrg.generateRevenue();
        //this.map = foodOrg.getRevenueMap();
//        System.out.println("map size>>"+map.size());

            //foodOrg = new FoodOrganization();
            this.map = foodOrg.getRevenueMap();
            System.out.println("map size>>"+map.size());
            
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        
//        Set keys = map.keySet();
//        System.out.println("key>>"+keys.size());
//        Iterator ite = keys.iterator();
//        
//        while(ite.hasNext()){
//            
//            String colorName = (String) ite.next();
//            //int qty = (int) map.get(colorName);
//            //dcd.setValue(qty, "Sales", colorName);
//        }
//        
        for(Entry<List<String>, Double> entry: map.entrySet()) {
        List<String> str = entry.getKey();
            if(str.get(0).equals("2021")) {
                System.out.println("year>>"+str.get(0)+" month>>"+str.get(1));
                    double price = entry.getValue();
                    dcd.setValue(price, "Sales", str.get(1));
            } 
        }
        
        //JFreeChart chart = ChartFactory.createBarChart("color report", "color", "val", dcd, PlotOrientation.VERTICAL, true, true, true);
        JFreeChart chart = ChartFactory.createLineChart("Sales Report", "Sales", "Revenue", dcd, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.BLACK);
        
        ChartPanel chartPn = new ChartPanel(chart);
        jPanel2.removeAll();
        jPanel2.add(chartPn);
        jPanel2.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel3 = new javax.swing.JPanel();
        ImageHeader4 = new javax.swing.JLabel();
        Title4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        revenueText = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        HeaderPanel3.setBackground(new java.awt.Color(255, 255, 255));
        HeaderPanel3.setPreferredSize(new java.awt.Dimension(1254, 116));

        ImageHeader4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/helpingHandsLogo.jpeg"))); // NOI18N

        Title4.setFont(new java.awt.Font("Palatino", 1, 48)); // NOI18N
        Title4.setText("Helping Hands");

        javax.swing.GroupLayout HeaderPanel3Layout = new javax.swing.GroupLayout(HeaderPanel3);
        HeaderPanel3.setLayout(HeaderPanel3Layout);
        HeaderPanel3Layout.setHorizontalGroup(
            HeaderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel3Layout.createSequentialGroup()
                .addComponent(ImageHeader4)
                .addGap(20, 20, 20)
                .addComponent(Title4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HeaderPanel3Layout.setVerticalGroup(
            HeaderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel3Layout.createSequentialGroup()
                .addGroup(HeaderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Title4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(jPanel2);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel5.setText("Date:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "2020", "2021" }));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel6.setText("Year:");

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel7.setText("Revenue:");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Show");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(revenueText)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton3)))
                .addGap(70, 70, 70)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(revenueText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String date = jDateChooser1.getDate().toString();
        String[] d = date.split(" ");
        System.out.println("date>>"+date);
        if(date.equals("") || revenueText.getText().equals("")){
            JOptionPane.showMessageDialog(null, "invalid input");
        }else{
            List<String> fullDate = Arrays.asList(d[d.length -1], d[1]);
            double val = Double.parseDouble(revenueText.getText());
            updateData(fullDate, val);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel3;
    private javax.swing.JLabel ImageHeader4;
    private javax.swing.JLabel Title4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField revenueText;
    // End of variables declaration//GEN-END:variables

    private void updateData(List<String> fullDate, double val) {
        System.out.println("fullDAte>>"+fullDate.get(0)+" "+fullDate.get(1)+" val>>"+val);
        for(Entry<List<String>, Double> entry: map.entrySet()) {
            List<String> str = entry.getKey();
            if(str.get(0).equals(fullDate.get(0)) && str.get(1).equals(fullDate.get(1))){
                System.out.println("if>>>");
                System.out.println("year>>"+str.get(0)+" month>>"+str.get(1));
                    double price = entry.getValue() + val;
                    map.put(str, price);
            } 
        }
        
//        if(color.equalsIgnoreCase("red")){
//            rVal = rVal + val;
//        }else if(color.equalsIgnoreCase("green")){
//            gVal= gVal + val;
//        }else if(color.equalsIgnoreCase("blue")){
//            bVal = bVal + val;
//        }
//        
//        map.clear();
//        map.put("red", rVal);
//        map.put("green", gVal);
//        map.put("blue", bVal);
        updateChart();
    }

    private void updateChart() {
        DefaultCategoryDataset dcd1 = new DefaultCategoryDataset();
        
//        Set keys = map.keySet();
//        Iterator ite = keys.iterator();
//        
//        while(ite.hasNext()){
//            
//            String colorName = (String) ite.next();
//            //int qty = (int) map.get(colorName);
//            //dcd.setValue(qty, "Sales", colorName);
//        }

            for(Entry<List<String>, Double> entry: map.entrySet()) {
            List<String> str = entry.getKey();
            if(str.get(0).equals("2021")) {
                    System.out.println("year>>"+str.get(0)+" month>>"+str.get(1)+ ">>>");
                    double price = entry.getValue();
                    dcd1.setValue(price, "Sales", str.get(1));
            } 
        }
        
        //JFreeChart chart = ChartFactory.createBarChart("color report", "color", "val", dcd, PlotOrientation.VERTICAL, true, true, true);
        JFreeChart chart1 = ChartFactory.createLineChart("Sales Report", "Sales", "Revenue", dcd1, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot plot1 = chart1.getCategoryPlot();
        plot1.setRangeGridlinePaint(Color.BLACK);
        
        ChartPanel chartPn1 = new ChartPanel(chart1);
        jPanel2.removeAll();
        jPanel2.add(chartPn1);
        jPanel2.updateUI();
    }
}
