/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Customer;

import Business.EcoSystem;
import Business.Organization.LegalServicesOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LawFirmWorkRequest;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author snehalchavan
 */
public class BookLawAppointment extends javax.swing.JPanel {

    /**
     * Creates new form BookLawAppointment
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    UserAccount userAccount;
    JSplitPane servicesSplitPane;
    LegalServicesOrganization legalOrg;
    String orgName = "Legal Services Organization";
    
    public BookLawAppointment(JPanel userProcessContainer, EcoSystem system, UserAccount userAccount,JSplitPane servicesSplitPane) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.servicesSplitPane = servicesSplitPane;
        
        for (int j = 0; j < system.getNetwork().getEnterpriseDirectory().getEnterprise("Finance").getOrganizationDirectory().getOrganizationList().size(); j++) {
            System.out.println("orgo>>>" + system.getNetwork().getEnterpriseDirectory().getEnterprise("Finance").getOrganizationDirectory().getOrganizationList().get(j).getName());
            if (system.getNetwork().getEnterpriseDirectory().getEnterprise("Finance").getOrganizationDirectory().getOrganizationList().get(j).getName() == orgName) {
                legalOrg = (LegalServicesOrganization) system.getNetwork().getEnterpriseDirectory().getEnterprise("Finance").getOrganizationDirectory().getOrganizationList().get(j);
                break;
            }
        }
        String name = (String) legalOrg.getDateArray().keySet().toArray()[0];
        System.out.println("name>>>>>>" + name);
        ArrayList<String> timeArray = legalOrg.getTimeSlot(name);
        System.out.println("1st date" + timeArray);
        System.out.println(system.getNetwork().getEnterpriseDirectory().getEnterprise("Medical").toString() + " medical...");
        for (int i = 0; i < timeArray.size(); i++) {
            jComboBox_timeSlotLaw.addItem(timeArray.get(i));
        }
        
        ArrayList<String> consultationtype = legalOrg.getConsultationtype();
        for(int i = 0; i < consultationtype.size(); i++){
            jComboBox1_consulatationtype.addItem(consultationtype.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        ImageHeader = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jPanel_appointmentLaw = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser_law = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_timeSlotLaw = new javax.swing.JComboBox<>();
        jButton_bookLaw = new javax.swing.JButton();
        jLabel_consulatationtype = new javax.swing.JLabel();
        jComboBox1_consulatationtype = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(178, 215, 229));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        ImageHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/helpingHandsLogo.jpeg"))); // NOI18N

        Title.setFont(new java.awt.Font("Palatino", 1, 48)); // NOI18N
        Title.setText("Helping Hands");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(ImageHeader)
                .addGap(20, 20, 20)
                .addComponent(Title)
                .addGap(0, 977, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_appointmentLaw.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        jLabel1.setText("Date :");

        jDateChooser_law.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser_lawMouseClicked(evt);
            }
        });
        jDateChooser_law.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser_lawPropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        jLabel2.setText("Time :");

        jComboBox_timeSlotLaw.setFont(new java.awt.Font("Palatino", 0, 13)); // NOI18N

        jButton_bookLaw.setBackground(new java.awt.Color(0, 0, 0));
        jButton_bookLaw.setFont(new java.awt.Font("Palatino", 1, 18)); // NOI18N
        jButton_bookLaw.setForeground(new java.awt.Color(255, 255, 255));
        jButton_bookLaw.setText("Book");
        jButton_bookLaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bookLawActionPerformed(evt);
            }
        });

        jLabel_consulatationtype.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        jLabel_consulatationtype.setText("Consultation Type :");

        jLabel3.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        jLabel3.setText("Book Appointment");

        javax.swing.GroupLayout jPanel_appointmentLawLayout = new javax.swing.GroupLayout(jPanel_appointmentLaw);
        jPanel_appointmentLaw.setLayout(jPanel_appointmentLawLayout);
        jPanel_appointmentLawLayout.setHorizontalGroup(
            jPanel_appointmentLawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_appointmentLawLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel_appointmentLawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_appointmentLawLayout.createSequentialGroup()
                        .addComponent(jLabel_consulatationtype)
                        .addContainerGap(139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_appointmentLawLayout.createSequentialGroup()
                        .addGroup(jPanel_appointmentLawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_bookLaw, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1_consulatationtype, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_appointmentLawLayout.createSequentialGroup()
                                .addGroup(jPanel_appointmentLawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel_appointmentLawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser_law, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(jComboBox_timeSlotLaw, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(82, 82, 82))))
            .addGroup(jPanel_appointmentLawLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel3))
        );
        jPanel_appointmentLawLayout.setVerticalGroup(
            jPanel_appointmentLawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_appointmentLawLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel_appointmentLawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser_law, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel_appointmentLawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_timeSlotLaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel_consulatationtype)
                .addGap(27, 27, 27)
                .addComponent(jComboBox1_consulatationtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton_bookLaw, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jPanel_appointmentLaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel_appointmentLaw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooser_lawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser_lawMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jDateChooser_lawMouseClicked

    private void jDateChooser_lawPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser_lawPropertyChange
        // TODO add your handling code here:
        if(jDateChooser_law.getDate()!= null){
            Date date = jDateChooser_law.getDate();
            SimpleDateFormat format1 = new SimpleDateFormat("MM-dd-yyyy");
            String date1 = format1.format(date);
            ArrayList<String> timeSlot1 = legalOrg.getTimeSlot(date1);
            jComboBox_timeSlotLaw.removeAllItems();
            for(int i=0;i< timeSlot1.size();i++){
                System.out.println("selected items....."+timeSlot1.get(i));
                jComboBox_timeSlotLaw.addItem(timeSlot1.get(i));
            }
        }
    }//GEN-LAST:event_jDateChooser_lawPropertyChange

    private void jButton_bookLawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bookLawActionPerformed
        // TODO add your handling code here:
        Date date = jDateChooser_law.getDate();
        SimpleDateFormat format1 = new SimpleDateFormat("MM-dd-yyyy");
        String date1 = format1.format(date);
        String timeSlot = (String) jComboBox_timeSlotLaw.getSelectedItem();
        String consultationType = (String) jComboBox1_consulatationtype.getSelectedItem();
        System.out.println("date++++++" + date1);
        ArrayList<String> timeSlot1 = legalOrg.getTimeSlot(date1);
        HashMap<String, ArrayList<String>> dateArray = legalOrg.getDateArray();

        timeSlot1.remove(timeSlot);
        System.out.println("deleted time" + timeSlot1);
        JOptionPane.showMessageDialog(null, "Appointment booked.");
        jComboBox_timeSlotLaw.removeAllItems();
        for(int i=0;i< timeSlot1.size();i++){
            System.out.println("deleted items....."+timeSlot1.get(i));

            jComboBox_timeSlotLaw.addItem(timeSlot1.get(i));
        }
        LawFirmWorkRequest request = new LawFirmWorkRequest();
        request.setSender(userAccount);
        request.setMessage("Book appointment");
        request.setTimeSlot(timeSlot);
        request.setDate(date1);
        request.setConsultationType(consultationType);
        userAccount.getWorkQueue().getWorkRequestList().add(request);

        if (legalOrg != null) {
            legalOrg.getWorkQueue().getWorkRequestList().add(request);

        }
    }//GEN-LAST:event_jButton_bookLawActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageHeader;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton_bookLaw;
    private javax.swing.JComboBox<String> jComboBox1_consulatationtype;
    private javax.swing.JComboBox<String> jComboBox_timeSlotLaw;
    private com.toedter.calendar.JDateChooser jDateChooser_law;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_consulatationtype;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanel_appointmentLaw;
    // End of variables declaration//GEN-END:variables
}
