/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Customer;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshikag
 */
public class HouseHoldChoreServices extends javax.swing.JPanel {

    /**
     * Creates new form HouseHoldChoreServices
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    DefaultTableModel model;
    UserAccount userAccount;
    JSplitPane servicesSplitPane;
    public HouseHoldChoreServices(JPanel userProcessContainer, EcoSystem business, UserAccount userAccount,JSplitPane servicesSplitPane) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.system = business;
        this.servicesSplitPane = servicesSplitPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        ImageHeader1 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        serviceTitle = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        houseHoldContentText = new javax.swing.JLabel();
        ViewServiceBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        ImageHeader1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/helpingHandsLogo.jpeg"))); // NOI18N

        Title1.setFont(new java.awt.Font("Palatino", 1, 48)); // NOI18N
        Title1.setText("Helping Hands");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addComponent(ImageHeader1)
                .addGap(20, 20, 20)
                .addComponent(Title1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Title1))
        );

        add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1165, -1));

        jPanel1.setBackground(new java.awt.Color(178, 215, 229));
        jPanel1.setToolTipText("");

        serviceTitle.setFont(new java.awt.Font("Palatino", 1, 24)); // NOI18N
        serviceTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serviceTitle.setText("House Hold Chore and Maintainence Services");

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/household_650x300.jpeg"))); // NOI18N

        houseHoldContentText.setFont(new java.awt.Font("Palatino", 0, 14)); // NOI18N
        houseHoldContentText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        houseHoldContentText.setText("<html>Family Resource is not a dedicated cleaning service, but our housekeeping services do include: <br> <ul> <li>Laundry </li> <li>Bed making and linen changes </li> <li>Dusting, vacuuming, and floor care (sweeping/mopping) </li> <li>Cleaning bathrooms and kitchen</li> <li>Taking out the trash</li> <li>Watering plants</li> <li>Help with organizational projects</li> <li>Pet care</li> </ul> </html>");
        houseHoldContentText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ViewServiceBtn.setBackground(new java.awt.Color(0, 0, 0));
        ViewServiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewServiceBtn.setText("View and book service");
        ViewServiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewServiceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(houseHoldContentText)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ViewServiceBtn)
                        .addGap(244, 244, 244)))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(serviceTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(houseHoldContentText, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewServiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(serviceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(393, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ViewServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewServiceBtnActionPerformed
        // TODO add your handling code here:
        BookHouseHoldService bookService = new BookHouseHoldService(userProcessContainer,system,userAccount,servicesSplitPane);
        servicesSplitPane.setRightComponent(bookService);
    }//GEN-LAST:event_ViewServiceBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageHeader1;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton ViewServiceBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel houseHoldContentText;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel serviceTitle;
    // End of variables declaration//GEN-END:variables
}
